DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS TOKEN;

CREATE TABLE USER(
    USER_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    USER_EMAIL VARCHAR(50),
    USER_PASSWORD VARCHAR(50),
    USER_ROLE VARCHAR(50)
);

CREATE TABLE TOKEN(
    TOKEN_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TOKEN_VALUE VARCHAR(100),
    USER_ID INT NOT NULL,
    FOREIGN KEY ( USER_ID ) REFERENCES USER(USER_ID)
);

INSERT INTO USER (USER_EMAIL, USER_PASSWORD, USER_ROLE)
   VALUES ('tester@test.com','password','user');

INSERT INTO USER (USER_EMAIL, USER_PASSWORD, USER_ROLE)
   VALUES ('admin@test.com','pwd','admin');
