DROP TABLE IF EXISTS USER;

CREATE TABLE USER(
    USER_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    USER_EMAIL VARCHAR(50),
    USER_PASSWORD VARCHAR(50),
    USER_ROLE VARCHAR(50)
);

--this is a comment

INSERT INTO USER (USER_EMAIL, USER_PASSWORD, USER_ROLE)
   VALUES ('tester@test.com','password','user');

INSERT INTO USER (USER_EMAIL, USER_PASSWORD, USER_ROLE)
   VALUES ('admin@test.com','pwd','admin');
